### ISSUE TITLE
Padronizar estrutura de pastas do dataset

### ISSUE THREAD

**Issue by rafaelmotaalves** [spgroup/mergedataset#46]
No dataset tem algumas pastas que não tão seguindo um padrão, como por exemplo as pastas:

./spring-boot/ea8107b6a53fa60b5f23b33e1b6d2e88bb60133c/original/Merge
./MPAndroidChart/af114d180da6ec5633d32c701ff5467f7629fcf3/original/Merge
./MPAndroidChart/9531ba69895cd64fce48038ffd8df2543eeea1d2/original/Merge

O ideal para gerar essas pastas e ler elas programaticamente seria que todas seguissem um mesmo padrão.

@leusonmario @pauloborba

**Comment by pauloborba** [comment]
@leusonmario é importante ajeitar isso logo

**Comment by leusonmario** [comment]
#47
